# Generated by Django 3.0.11 on 2021-03-04 08:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('valid', models.BooleanField(default=True)),
                ('expiration_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
