# Generated by Django 3.0.11 on 2021-03-04 08:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, choices=[('Alberta', 'AB'), ('British Columbia', 'BC'), ('Manitoba', 'MB'), ('New Brunswick', 'NB'), ('Newfoundland and Labrador', 'NL'), ('Nova Scotia', 'NS'), ('Ontario', 'ON'), ('Prince Edward Island', 'PE'), ('Quebec', 'QC'), ('Saskatchewan', 'SK'), ('Northwest Territories', 'NWT'), ('Nunavut', 'NT'), ('Yukon', 'YT')], max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
